name: Windows CI - Build C++ raylib Game

permissions:
  contents: write 

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ilammy/msvc-dev-cmd@v1.4.1

      - name: Build The Game
        run: |
          .\scripts\msvc-build-raylib.bat
          .\scripts\msvc-build-debug.bat

      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
