name: Windows CI - Build C++ raylib Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - uses: ilammy/msvc-dev-cmd@v1.4.1

      - name: Build with build.bat
        run: |
          .\scripts\msvc-build-raylib.bat
          .\scripts\msvc-build-debug.bat
